### ISSUE TITLE
训练完成后，将训练得到的epoch_160.pth 替换 render.pth 后运行报错

### ISSUE THREAD

**Issue by yancccc** [kleinlee/DH_live#36]
训练完成后，将训练得到的epoch_160.pth 替换 render.pth 后运行报错：

(dhlive) E:\shuziren\DH_live-main>python demo.py video_data/test video_data/audio0.wav out.mp4
(256, 256, 3)
Video path is set to: video_data/test
Audio path is set to: video_data/audio0.wav
output video name is set to: out.mp4
E:\shuziren\DH_live-main\talkingface\audio_model.py:46: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.__net.load_state_dict(torch.load(ckpt_path))
E:\shuziren\DH_live-main\talkingface\render_model.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(ckpt_path)
Traceback (most recent call last):
  File "E:\shuziren\DH_live-main\demo.py", line 63, in <module>
    main()
  File "E:\shuziren\DH_live-main\demo.py", line 30, in main
    renderModel.loadModel("checkpoint/epoch_160.pth")
  File "E:\shuziren\DH_live-main\talkingface\render_model.py", line 38, in loadModel
    self.__net.load_state_dict(checkpoint)
  File "E:\Anaconda3\envs\dhlive\lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DINet_five_Ref:
        Missing key(s) in state_dict: "source_in_conv.0.conv.weight", "source_in_conv.0.conv.bias", "source_in_conv.0.norm.weight", "source_in_conv.0.norm.bias", "source_in_conv.0.norm.running_mean", "source_in_conv.0.norm.running_var", "source_in_conv.1.conv.weight", "source_in_conv.1.conv.bias", "source_in_conv.1.norm.weight", "source_in_conv.1.norm.bias", "source_in_conv.1.norm.running_mean", "source_in_conv.1.norm.running_var", "source_in_conv.2.conv.weight", "source_in_conv.2.conv.bias", "source_in_conv.2.norm.weight", "source_in_conv.2.norm.bias", "source_in_conv.2.norm.running_mean", "source_in_conv.2.norm.running_var", "ref_in_conv.0.conv.weight", "ref_in_conv.0.conv.bias", "ref_in_conv.0.norm.weight", "ref_in_conv.0.norm.bias", "ref_in_conv.0.norm.running_mean", "ref_in_conv.0.norm.running_var", "ref_in_conv.1.conv.weight", "ref_in_conv.1.conv.bias", "ref_in_conv.1.norm.weight", "ref_in_conv.1.norm.bias", "ref_in_conv.1.norm.running_mean", "ref_in_conv.1.norm.running_var", "ref_in_conv.2.conv.weight", "ref_in_conv.2.conv.bias", "ref_in_conv.2.norm.weight", "ref_in_conv.2.norm.bias", "ref_in_conv.2.norm.running_mean", "ref_in_conv.2.norm.running_var", "trans_conv.0.conv.weight", "trans_conv.0.conv.bias", "trans_conv.0.norm.weight", "trans_conv.0.norm.bias", "trans_conv.0.norm.running_mean", "trans_conv.0.norm.running_var", "trans_conv.1.conv.weight", "trans_conv.1.conv.bias", "trans_conv.1.norm.weight", "trans_conv.1.norm.bias", "trans_conv.1.norm.running_mean", "trans_conv.1.norm.running_var", "trans_conv.2.conv.weight", "trans_conv.2.conv.bias", "trans_conv.2.norm.weight", "trans_conv.2.norm.bias", "trans_conv.2.norm.running_mean", "trans_conv.2.norm.running_var", "trans_conv.3.conv.weight", "trans_conv.3.conv.bias", "trans_conv.3.norm.weight", "trans_conv.3.norm.bias", "trans_conv.3.norm.running_mean", "trans_conv.3.norm.running_var", "trans_conv.4.conv.weight", "trans_conv.4.conv.bias", "trans_conv.4.norm.weight", "trans_conv.4.norm.bias", "trans_conv.4.norm.running_mean", "trans_conv.4.norm.running_var", "trans_conv.5.conv.weight", "trans_conv.5.conv.bias", "trans_conv.5.norm.weight", "trans_conv.5.norm.bias", "trans_conv.5.norm.running_mean", "trans_conv.5.norm.running_var", "trans_conv.6.conv.weight", "trans_conv.6.conv.bias", "trans_conv.6.norm.weight", "trans_conv.6.norm.bias", "trans_conv.6.norm.running_mean", "trans_conv.6.norm.running_var", "trans_conv.7.conv.weight", "trans_conv.7.conv.bias", "trans_conv.7.norm.weight", "trans_conv.7.norm.bias", "trans_conv.7.norm.running_mean", "trans_conv.7.norm.running_var", "trans_conv.8.conv.weight", "trans_conv.8.conv.bias", "trans_conv.8.norm.weight", "trans_conv.8.norm.bias", "trans_conv.8.norm.running_mean", "trans_conv.8.norm.running_var", "appearance_conv_list.0.0.conv1.weight", "appearance_conv_list.0.0.conv1.bias", "appearance_conv_list.0.0.conv2.weight", "appearance_conv_list.0.0.conv2.bias", "appearance_conv_list.0.0.norm1.weight", "appearance_conv_list.0.0.norm1.bias", "appearance_conv_list.0.0.norm1.running_mean", "appearance_conv_list.0.0.norm1.running_var", "appearance_conv_list.0.0.norm2.weight", "appearance_conv_list.0.0.norm2.bias", "appearance_conv_list.0.0.norm2.running_mean", "appearance_conv_list.0.0.norm2.running_var", "appearance_conv_list.0.1.conv1.weight", "appearance_conv_list.0.1.conv1.bias", "appearance_conv_list.0.1.conv2.weight", "appearance_conv_list.0.1.conv2.bias", "appearance_conv_list.0.1.norm1.weight", "appearance_conv_list.0.1.norm1.bias", "appearance_conv_list.0.1.norm1.running_mean", "appearance_conv_list.0.1.norm1.running_var", "appearance_conv_list.0.1.norm2.weight", "appearance_conv_list.0.1.norm2.bias", "appearance_conv_list.0.1.norm2.running_mean", "appearance_conv_list.0.1.norm2.running_var", "appearance_conv_list.1.0.conv1.weight", "appearance_conv_list.1.0.conv1.bias", "appearance_conv_list.1.0.conv2.weight", "appearance_conv_list.1.0.conv2.bias", "appearance_conv_list.1.0.norm1.weight", "appearance_conv_list.1.0.norm1.bias", "appearance_conv_list.1.0.norm1.running_mean", "appearance_conv_list.1.0.norm1.running_var", "appearance_conv_list.1.0.norm2.weight", "appearance_conv_list.1.0.norm2.bias", "appearance_conv_list.1.0.norm2.running_mean", "appearance_conv_list.1.0.norm2.running_var", "appearance_conv_list.1.1.conv1.weight", "appearance_conv_list.1.1.conv1.bias", "appearance_conv_list.1.1.conv2.weight", "appearance_conv_list.1.1.conv2.bias", "appearance_conv_list.1.1.norm1.weight", "appearance_conv_list.1.1.norm1.bias", "appearance_conv_list.1.1.norm1.running_mean", "appearance_conv_list.1.1.norm1.running_var", "appearance_conv_list.1.1.norm2.weight", "appearance_conv_list.1.1.norm2.bias", "appearance_conv_list.1.1.norm2.running_mean", "appearance_conv_list.1.1.norm2.running_var", "adaAT.commn_linear.0.weight", "adaAT.commn_linear.0.bias", "adaAT.scale.0.weight", "adaAT.scale.0.bias", "adaAT.rotation.0.weight", "adaAT.rotation.0.bias", "adaAT.translation.0.weight", "adaAT.translation.0.bias", "out_conv.0.conv.weight", "out_conv.0.conv.bias", "out_conv.0.norm.weight", "out_conv.0.norm.bias", "out_conv.0.norm.running_mean", "out_conv.0.norm.running_var", "out_conv.1.conv.weight", "out_conv.1.conv.bias", "out_conv.1.norm.weight", "out_conv.1.norm.bias", "out_conv.1.norm.running_mean", "out_conv.1.norm.running_var", "out_conv.2.conv1.weight", "out_conv.2.conv1.bias", "out_conv.2.conv2.weight", "out_conv.2.conv2.bias", "out_conv.2.norm1.weight", "out_conv.2.norm1.bias", "out_conv.2.norm1.running_mean", "out_conv.2.norm1.running_var", "out_conv.2.norm2.weight", "out_conv.2.norm2.bias", "out_conv.2.norm2.running_mean", "out_conv.2.norm2.running_var", "out_conv.3.conv.weight", "out_conv.3.conv.bias", "out_conv.3.norm.weight", "out_conv.3.norm.bias", "out_conv.3.norm.running_mean", "out_conv.3.norm.running_var", "out_conv.4.weight", "out_conv.4.bias".
        Unexpected key(s) in state_dict: "epoch", "state_dict", "optimizer".

**Comment by qwert1887** [comment]
自行提取epoch 160里面的 state_dict结构

**Comment by yancccc** [comment]
提取epoch 160里面的 state_dict结构：是'net_g', 'net_d'     
(dhlive) E:\shuziren\DH_live-main>python
Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:38:46) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> checkpoint = torch.load("checkpoint/epoch_160.pth")
<stdin>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
>>> print(checkpoint['state_dict'].keys())
dict_keys(['net_g', 'net_d'])
>>>

**Comment by yancccc** [comment]
> 自行提取epoch 160里面的 state_dict结构

提取epoch 160里面的 state_dict结构：是'net_g', 'net_d'
(dhlive) E:\shuziren\DH_live-main>python
Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:38:46) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

import torch
checkpoint = torch.load("checkpoint/epoch_160.pth")
:1: FutureWarning: You are using torch.load with weights_only=False (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for weights_only will be flipped to True. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via torch.serialization.add_safe_globals. We recommend you start setting weights_only=True for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
print(checkpoint['state_dict'].keys())
dict_keys(['net_g', 'net_d'])

**Comment by qwert1887** [comment]
提取net_g

**Comment by yancccc** [comment]
> 提取net_g

好了，就是有点糊
![image](https://github.com/user-attachments/assets/5cbb0e0e-4883-4d37-8fe2-8468281e3c82)

**Comment by yancccc** [comment]
![image](https://github.com/user-attachments/assets/9998bc25-a5ee-44e3-b050-3661f248686a)

**Comment by qwert1887** [comment]
你也用的单人视频吗

**Comment by yancccc** [comment]
我用了几十个视频

**Comment by zhangyushushu** [comment]
请问能告诉我怎么提取么？我也这个问题不会搞

**Comment by lonngxiang** [comment]
> > 提取net_g
> 
> 好了，就是有点糊 ![image](https://private-user-images.githubusercontent.com/26217359/370983565-5cbb0e0e-4883-4d37-8fe2-8468281e3c82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0ODM5MDAsIm5iZiI6MTcyNzQ4MzYwMCwicGF0aCI6Ii8yNjIxNzM1OS8zNzA5ODM1NjUtNWNiYjBlMGUtNDg4My00ZDM3LThmZTItODQ2ODI4MWUzYzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDAwMzMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMzQxYzRlOWE5MTQ5ZmQzMTBiZWMwMjJlN2NiZjU3YzhjZTE3OGNiOWI5ZjE2MzUzMWQxMmYxZWZhYjA2MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QAXhKb9LEaqxGJaK2VAEBi-VuMIBiRCeIm89XqLEIjU)

麻烦问下具体怎么提取的呢

**Comment by lonngxiang** [comment]
> 提取net_g

麻烦怎么提取转换成render.pth呢

**Comment by lonngxiang** [comment]
转换后加载运行报错
```
python demo1.py /home/loong/Downloads/loong/loong1_bk video_data/audio0.wav 3.mp4
(256, 256, 3)
Video path is set to: /home/loong/Downloads/loong/loong1_bk
Audio path is set to: video_data/audio0.wav
output video name is set to: 3.mp4
/home/loong/miniconda3/envs/dh_live/lib/python3.12/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator PCA from version 1.3.0 when using version 1.5.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/ai/DH_live/talkingface/audio_model.py:46: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.__net.load_state_dict(torch.load(ckpt_path))
/ai/DH_live/talkingface/render_model.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(ckpt_path)
请检查当前视频， 错误帧数： 18
Traceback (most recent call last):
  File "/ai/DH_live/demo1.py", line 63, in <module>
    main()
  File "/ai/DH_live/demo1.py", line 33, in main
    renderModel.reset_charactor(video_path, pkl_path)
  File "/ai/DH_live/talkingface/render_model.py", line 46, in reset_charactor
    prepare_video_data(video_path, Path_pkl, ref_img_index_list)
  File "/ai/DH_live/talkingface/run_utils.py", line 226, in prepare_video_data
    ref_img = get_ref_images_fromVideo(cap_input, ref_img_index_list, pts_driven[:, :, :2])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ai/DH_live/talkingface/data/few_shot_dataset.py", line 78, in get_ref_images_fromVideo
    ref_img = generate_ref(frame, ref_keypoints[index])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ai/DH_live/talkingface/data/few_shot_dataset.py", line 50, in generate_ref
    crop_coords = crop_face(keypoints, size=img.shape[:2], is_train=is_train)
                                            ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by lonngxiang** [comment]
单人四个视频训练，160轮运行效果，还是很差
![image](https://github.com/user-attachments/assets/eb6bd381-70f9-4bc9-85a4-8bea65819484)

**Comment by gzyhy** [comment]
> 提取net_g

提取net_g,是怎样操作的，用什么python命令

**Comment by hjj-lmx** [comment]
> > 提取net_g
> 
> 好了，就是有点糊 ![image](https://private-user-images.githubusercontent.com/26217359/370983565-5cbb0e0e-4883-4d37-8fe2-8468281e3c82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mzg5MTMsIm5iZiI6MTcyODYzODYxMywicGF0aCI6Ii8yNjIxNzM1OS8zNzA5ODM1NjUtNWNiYjBlMGUtNDg4My00ZDM3LThmZTItODQ2ODI4MWUzYzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA5MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YmE1MDdhMGEwYzMwYTQ5NTU4MDY1MGUwZDk4OGU4M2IxMDE4NjE2YWUxNDUxMzgzNTg1OWUzZDExMzhmNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-JzOsT892FowG1dBVkYo_pwigVEbFxipFYxENNur3n8)
请问一下，具体怎么提取的

**Comment by kleinlee** [comment]
https://github.com/kleinlee/DH_live/issues/45#issuecomment-2382860629
