### ISSUE TITLE
自己训练的模型，替换render.pth，报加载异常。

### ISSUE THREAD

**Issue by zhangziliang04** [kleinlee/DH_live#45]
![image](https://github.com/user-attachments/assets/ac9963b9-273d-4770-8bed-c73d6a4013d8)

详细异常信息如上图所示。不知道作者能不能提供一份使用自己训练的模型的推理代码，类似demo.py

**Comment by joisonwk** [comment]
我也是报这个错误
```python demo.py video_data/test video_data/audio0.wav output/1.mp4
(256, 256, 3)
Video path is set to: video_data/test
Audio path is set to: video_data/audio0.wav
output video name is set to: output/1.mp4
E:\metahuman\.venv\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator PCA from version 1.3.0 when using version 1.5.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
E:\metahuman\DH_live\talkingface\audio_model.py:46: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). 
In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.__net.load_state_dict(torch.load(ckpt_path))
E:\metahuman\DH_live\talkingface\render_model.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. 
It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you 
don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(ckpt_path)
Traceback (most recent call last):
  File "E:\metahuman\DH_live\demo.py", line 63, in <module>
    main()
  File "E:\metahuman\DH_live\demo.py", line 30, in main
    renderModel.loadModel("checkpoint/render.pth")
  File "E:\metahuman\DH_live\talkingface\render_model.py", line 38, in loadModel
    self.__net.load_state_dict(checkpoint)
  File "E:\metahuman\.venv\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DINet_five_Ref:
        Missing key(s) in state_dict: "source_in_conv.0.conv.weight", "source_in_conv.0.conv.bias", "source_in_conv.0.norm.weight", "source_in_conv.0.norm.bias", "source_in_conv.0.norm.running_mean", "source_in_conv.0.norm.running_var", "source_in_conv.1.conv.weight", "source_in_conv.1.conv.bias", "source_in_conv.1.norm.weight", "source_in_conv.1.norm.bias", "source_in_conv.1.norm.running_mean", "source_in_conv.1.norm.running_var", "source_in_conv.2.conv.weight", "source_in_conv.2.conv.bias", "source_in_conv.2.norm.weight", "source_in_conv.2.norm.bias", "source_in_conv.2.norm.running_mean", "source_in_conv.2.norm.running_var", "ref_in_conv.0.conv.weight", "ref_in_conv.0.conv.bias", "ref_in_conv.0.norm.weight", "ref_in_conv.0.norm.bias", "ref_in_conv.0.norm.running_mean", "ref_in_conv.0.norm.running_var", "ref_in_conv.1.conv.weight", "ref_in_conv.1.conv.bias", "ref_in_conv.1.norm.weight", "ref_in_conv.1.norm.bias", "ref_in_conv.1.norm.running_mean", "ref_in_conv.1.norm.running_var", "ref_in_conv.2.conv.weight", "ref_in_conv.2.conv.bias", "ref_in_conv.2.norm.weight", "ref_in_conv.2.norm.bias", "ref_in_conv.2.norm.running_mean", "ref_in_conv.2.norm.running_var", "trans_conv.0.conv.weight", "trans_conv.0.conv.bias", "trans_conv.0.norm.weight", "trans_conv.0.norm.bias", "trans_conv.0.norm.running_mean", "trans_conv.0.norm.running_var", "trans_conv.1.conv.weight", "trans_conv.1.conv.bias", "trans_conv.1.norm.weight", "trans_conv.1.norm.bias", "trans_conv.1.norm.running_mean", "trans_conv.1.norm.running_var", "trans_conv.2.conv.weight", "trans_conv.2.conv.bias", "trans_conv.2.norm.weight", "trans_conv.2.norm.bias", "trans_conv.2.norm.running_mean", "trans_conv.2.norm.running_var", "trans_conv.3.conv.weight", "trans_conv.3.conv.bias", "trans_conv.3.norm.weight", "trans_conv.3.norm.bias", "trans_conv.3.norm.running_mean", "trans_conv.3.norm.running_var", "trans_conv.4.conv.weight", "trans_conv.4.conv.bias", "trans_conv.4.norm.weight", "trans_conv.4.norm.bias", "trans_conv.4.norm.running_mean", "trans_conv.4.norm.running_var", "trans_conv.5.conv.weight", "trans_conv.5.conv.bias", "trans_conv.5.norm.weight", "trans_conv.5.norm.bias", "trans_conv.5.norm.running_mean", "trans_conv.5.norm.running_var", "trans_conv.6.conv.weight", "trans_conv.6.conv.bias", "trans_conv.6.norm.weight", "trans_conv.6.norm.bias", "trans_conv.6.norm.running_mean", "trans_conv.6.norm.running_var", "trans_conv.7.conv.weight", "trans_conv.7.conv.bias", "trans_conv.7.norm.weight", "trans_conv.7.norm.bias", "trans_conv.7.norm.running_mean", "trans_conv.7.norm.running_var", "trans_conv.8.conv.weight", "trans_conv.8.conv.bias", "trans_conv.8.norm.weight", "trans_conv.8.norm.bias", "trans_conv.8.norm.running_mean", "trans_conv.8.norm.running_var", "appearance_conv_list.0.0.conv1.weight", "appearance_conv_list.0.0.conv1.bias", "appearance_conv_list.0.0.conv2.weight", "appearance_conv_list.0.0.conv2.bias", "appearance_conv_list.0.0.norm1.weight", "appearance_conv_list.0.0.norm1.bias", "appearance_conv_list.0.0.norm1.running_mean", "appearance_conv_list.0.0.norm1.running_var", "appearance_conv_list.0.0.norm2.weight", "appearance_conv_list.0.0.norm2.bias", "appearance_conv_list.0.0.norm2.running_mean", "appearance_conv_list.0.0.norm2.running_var", "appearance_conv_list.0.1.conv1.weight", "appearance_conv_list.0.1.conv1.bias", "appearance_conv_list.0.1.conv2.weight", "appearance_conv_list.0.1.conv2.bias", "appearance_conv_list.0.1.norm1.weight", "appearance_conv_list.0.1.norm1.bias", "appearance_conv_list.0.1.norm1.running_mean", "appearance_conv_list.0.1.norm1.running_var", "appearance_conv_list.0.1.norm2.weight", "appearance_conv_list.0.1.norm2.bias", "appearance_conv_list.0.1.norm2.running_mean", "appearance_conv_list.0.1.norm2.running_var", "appearance_conv_list.1.0.conv1.weight", "appearance_conv_list.1.0.conv1.bias", "appearance_conv_list.1.0.conv2.weight", "appearance_conv_list.1.0.conv2.bias", "appearance_conv_list.1.0.norm1.weight", "appearance_conv_list.1.0.norm1.bias", "appearance_conv_list.1.0.norm1.running_mean", "appearance_conv_list.1.0.norm1.running_var", "appearance_conv_list.1.0.norm2.weight", "appearance_conv_list.1.0.norm2.bias", "appearance_conv_list.1.0.norm2.running_mean", "appearance_conv_list.1.0.norm2.running_var", "appearance_conv_list.1.1.conv1.weight", "appearance_conv_list.1.1.conv1.bias", "appearance_conv_list.1.1.conv2.weight", "appearance_conv_list.1.1.conv2.bias", "appearance_conv_list.1.1.norm1.weight", "appearance_conv_list.1.1.norm1.bias", "appearance_conv_list.1.1.norm1.running_mean", "appearance_conv_list.1.1.norm1.running_var", "appearance_conv_list.1.1.norm2.weight", "appearance_conv_list.1.1.norm2.bias", "appearance_conv_list.1.1.norm2.running_mean", "appearance_conv_list.1.1.norm2.running_var", "adaAT.commn_linear.0.weight", "adaAT.commn_linear.0.bias", "adaAT.scale.0.weight", "adaAT.scale.0.bias", "adaAT.rotation.0.weight", "adaAT.rotation.0.bias", "adaAT.translation.0.weight", "adaAT.translation.0.bias", "out_conv.0.conv.weight", "out_conv.0.conv.bias", "out_conv.0.norm.weight", "out_conv.0.norm.bias", "out_conv.0.norm.running_mean", "out_conv.0.norm.running_var", "out_conv.1.conv.weight", "out_conv.1.conv.bias", "out_conv.1.norm.weight", "out_conv.1.norm.bias", "out_conv.1.norm.running_mean", "out_conv.1.norm.running_var", "out_conv.2.conv1.weight", "out_conv.2.conv1.bias", "out_conv.2.conv2.weight", "out_conv.2.conv2.bias", "out_conv.2.norm1.weight", "out_conv.2.norm1.bias", "out_conv.2.norm1.running_mean", "out_conv.2.norm1.running_var", "out_conv.2.norm2.weight", "out_conv.2.norm2.bias", "out_conv.2.norm2.running_mean", "out_conv.2.norm2.running_var", "out_conv.3.conv.weight", "out_conv.3.conv.bias", "out_conv.3.norm.weight", "out_conv.3.norm.bias", "out_conv.3.norm.running_mean", "out_conv.3.norm.running_var", "out_conv.4.weight", "out_conv.4.bias".
        Unexpected key(s) in state_dict: "epoch", "state_dict", "optimizer".
```

**Comment by zhangziliang04** [comment]
亲测可用。谢谢。
