### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zhangsanfather** [kleinlee/DH_live#46]
![微信图片_20240930141405](https://github.com/user-attachments/assets/f039c24d-66a6-4cc8-b68d-642f1e588bf7)
===> Epoch[2](0/27): Loss_DI: 0.2643 Loss_GI: 0.2390 Loss_perception: 7.0056 lr_g = 0.0001000 lr_d = 0.0001000
===> Epoch[2](1/27): Loss_DI: 0.2647 Loss_GI: 0.2664 Loss_perception: 6.9089 lr_g = 0.0001000 lr_d = 0.0001000
===> Epoch[2](2/27): Loss_DI: 0.2565 Loss_GI: 0.2877 Loss_perception: 6.6394 lr_g = 0.0001000 lr_d = 0.0001000
===> Epoch[2](3/27): Loss_DI: 0.2627 Loss_GI: 0.2995 Loss_perception: 6.7119 lr_g = 0.0001000 lr_d = 0.0001000
Traceback (most recent call last):
  File "F:\ai\DH_live\train\train_render_model.py", line 103, in <module>
    for iteration, data in enumerate(training_data_loader):
  File "F:\ai\DH_live\py311\Lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "F:\ai\DH_live\py311\Lib\site-packages\torch\utils\data\dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ai\DH_live\py311\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ai\DH_live\py311\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "F:\ai\DH_live\train\..\talkingface\data\few_shot_dataset.py", line 151, in __getitem__
    target_keypoints = self.driving_keypoints[video_index][current_clip]
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: index 268 is out of bounds for axis 0 with size 267

**Comment by Eikwang** [comment]
素材片段太长了
