### ISSUE TITLE
训练数据集处理报错：Singular matrix

### ISSUE THREAD

**Issue by gushuaialan1** [kleinlee/DH_live#56]
训练第一步
python train/data_preparation_face.py dir_to_data  

结果报错如下

> I0000 00:00:1728819618.229953 1152263 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.54.15), renderer: NVIDIA A100 80GB PCIe/PCIe/SSE2
W0000 00:00:1728819618.231591 1152204 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1728819618.242070 1152194 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 834/836 [02:07<00:00,  6.55it/s]
关键点已提取███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 834/836 [02:07<00:00,  6.47it/s]
人脸活动范围：0:1088, 0:885
  0%|                                                                                                                                                                                   | 0/4 [02:08<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/DH_live/train/data_preparation_face.py", line 275, in <module>
    main()
  File "/mnt/DH_live/train/data_preparation_face.py", line 272, in main
    run(video_path)
  File "/mnt/DH_live/train/data_preparation_face.py", line 229, in run
    mat_list, pts_normalized_list, face_pts_mean_personal = calc_face_mat(pts_driven, face_pts_mean)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/DH_live/train/../talkingface/run_utils.py", line 44, in calc_face_mat
    keypoints_normalized = np.linalg.inv(rotationMatrix).dot(keypoints).T
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/dhlive/lib/python3.12/site-packages/numpy/linalg/linalg.py", line 561, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/dhlive/lib/python3.12/site-packages/numpy/linalg/linalg.py", line 112, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

**Comment by kleinlee** [comment]
视频人脸检测失败才会出现。 需要复查视频，保证视频每一帧都有且只有一个人脸。

**Comment by gushuaialan1** [comment]
> 视频人脸检测失败才会出现。 需要复查视频，保证视频每一帧都有且只有一个人脸。

解决了，第一裁剪了视频人脸比例更大一点，第二重命名了（按照教程的video1那种命名方式），第三视频长度缩短（原来是每段30秒左右，缩减为15秒以内），同样的视频就没有再出问题。
