### ISSUE TITLE
demo_avatar.py报错

### ISSUE THREAD

**Issue by TheChosenPerson** [kleinlee/DH_live#78]
我拉取项目之后直接运行data_avatar.py产生了报错，大佬，是我有什么没有拉取下来吗？

```log
Traceback (most recent call last):
  File "G:\DH_live\demo_avatar.py", line 18, in <module>
    renderModel.reset_charactor(video_path, pkl_path)
  File "G:\DH_live\talkingface\render_model.py", line 46, in reset_charactor
    prepare_video_data(video_path, Path_pkl, ref_img_index_list)
  File "G:\DH_live\talkingface\run_utils.py", line 267, in prepare_video_data
    mat_list, pts_normalized_list, face_pts_mean_personal, face_mask_pts = video_pts_process(pts_driven)
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\DH_live\talkingface\run_utils.py", line 138, in video_pts_process
    mat_list, pts_normalized_list, face_pts_mean_personal = calc_face_mat(pts_array_origin, face_pts_mean)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\DH_live\talkingface\run_utils.py", line 81, in calc_face_mat
    x_new = x_new.reshape(len(x_new), 478, 3)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 64719 into shape (153,478,3)
```

**Comment by TheChosenPerson** [comment]
我使用data_preparation.py运行出来一个之后，用新的这个也会产生上面的那个报错。

**Comment by kleinlee** [comment]
嗯，新代码改了一点东西导致旧代码出问题，夜间会更新
