### ISSUE TITLE
the error of train

### ISSUE THREAD

**Issue by YangYu8510** [kleinlee/DH_live#85]
Traceback (most recent call last):
  File "E:\project\test\DH_live\train\train_render_model.py", line 104, in <module>
    for iteration, data in enumerate(training_data_loader):
  File "E:\project\test\DH_live\py311\Lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "E:\project\test\DH_live\py311\Lib\site-packages\torch\utils\data\dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\test\DH_live\py311\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\project\test\DH_live\py311\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "E:\project\test\DH_live\talkingface\data\few_shot_dataset.py", line 151, in __getitem__
    target_keypoints = self.driving_keypoints[video_index][current_clip]
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: index 150 is out of bounds for axis 0 with size 150

在训练时出现这个问题，但是当我测试第一轮的时候有些是正常的，现在大概是几十个视频，每个视频大概是5s

**Comment by YangYu8510** [comment]
我是使用上百个6s的视频，然后第一轮没有问题，第二轮报错这个，然后减少视频数量，结果第一轮就报错了

**Comment by kleinlee** [comment]
原版DH_live已不再获支持，目前关闭此issue。
